services:
  - type: web
    name: stock-management
    env: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
  startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.7
databases:
  - name: stock-db
    databaseName: stock
    user: stock
